services:

  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: backend
    container_name: g4f-backend
    working_dir: /var/www
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - g4f

  frontend:
    build:
      context: .
      dockerfile: dockerfile
      target: frontend
    container_name: g4f-frontend
    networks:
      - g4f
    ports:
    - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: dockerfile
      target: nginx
    container_name: g4f-nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
    depends_on:
      - backend
      - frontend
    networks:
      - g4f

  db:
    image: mariadb:11
    container_name: g4f-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: g4f
      MYSQL_USER: g4f
      MYSQL_PASSWORD: g4f
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - g4f

networks:
  g4f:

volumes:
  db_data: