server {
    listen 80;

    server_name localhost;

    # =========================
    # REACT
    # =========================
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }


    # =========================
    # LARAVEL
    # =========================
    location ^~ /api/ {
        root /var/www/public;

        try_files $uri $uri/ /index.php?$query_string;
    }


    # =========================
    # PHP-FPM / LARAVEL
    # =========================
    location ~ \.php$ {
        root /var/www/public;

        try_files $uri =404;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/public;

        fastcgi_pass backend:9000;
    }
}

# server {
#     listen 80;

#     server_name localhost;

#     root /usr/share/nginx/html;
#     index index.html;

#     location / {
#         try_files $uri $uri/ /index.html;
#     }
# }